/**
 * Writes the reference pages that restate what the code already says.
 *
 * A hand-maintained list of enum values or quality flags drifts exactly as fast
 * as a hand-maintained API page, and is trusted for longer because it looks
 * stable. These three pages are generated and CI fails if the committed copies
 * differ from what this script produces.
 */

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';
import * as schema from '@clycites/schema';
import { CORE_ENTITIES, envelopeShape, SCHEMA_VERSION } from '@clycites/schema';

import { ENTITY_SCHEMAS } from '../src/records/entity-registry.js';
import { FLAG_GLOSSARY } from '../src/records/lender-report.js';

const DOCS = resolve(dirname(fileURLToPath(import.meta.url)), '../../../docs/reference');

const PREAMBLE = (source: string) =>
  `<!-- Generated by apps/kernel/scripts/generate-docs-reference.ts. Do not edit.\n` +
  `     Source: ${source}. Run \`pnpm docs:reference\`. -->\n\n`;

/** Zod v4 keeps the concrete class behind `_zod`; the option list is public. */
const enumValues = (value: unknown): string[] | null =>
  value instanceof z.ZodEnum ? Object.values(value.enum as Record<string, string>) : null;

/* ── enumerations ─────────────────────────────────────────────────────── */

const enumerations = () => {
  const rows = Object.entries(schema as Record<string, unknown>)
    .map(([name, value]) => [name, enumValues(value)] as const)
    .filter((pair): pair is readonly [string, string[]] => pair[1] !== null)
    .sort(([a], [b]) => a.localeCompare(b));

  const body = rows
    .map(
      ([name, values]) =>
        `### \`${name}\`\n\n` +
        values.map((v) => `- \`${v}\``).join('\n') +
        '\n',
    )
    .join('\n');

  return (
    PREAMBLE('packages/schema/src/enums.ts') +
    `# Enumerations\n\n` +
    `Every closed vocabulary in schema \`${SCHEMA_VERSION}\`, as the code holds it.\n` +
    `A value absent from this page is a value the kernel refuses.\n\n` +
    `Why each list stops where it does is in the source, which carries the\n` +
    `reasoning as comments: [\`packages/schema/src/enums.ts\`](https://github.com/ClyCites/Kernel/blob/staging/packages/schema/src/enums.ts).\n` +
    `The two that decide most are [\`MeasurementMethod\`](../concepts/provenance.md)\n` +
    `and [\`LawfulBasis\`](../concepts/lawful-basis.md).\n\n` +
    `${rows.length} enumerations.\n\n` +
    body
  );
};

/* ── entities ─────────────────────────────────────────────────────────── */

const commons = new Set(Object.keys(envelopeShape));

const fieldsOf = (type: string): string[] => {
  const entity = (ENTITY_SCHEMAS as Record<string, unknown>)[type];
  if (!entity) return [];
  const shape = (entity as { shape?: Record<string, unknown> }).shape;
  return shape ? Object.keys(shape).filter((key) => !commons.has(key)) : [];
};

const entities = () => {
  const body = CORE_ENTITIES.map((type) => {
    const own = fieldsOf(type);
    return (
      `### \`${type}\`\n\n` +
      (own.length === 0
        ? 'No fields of its own — the envelope carries everything it asserts.\n'
        : own.map((f) => `- \`${f}\``).join('\n') + '\n')
    );
  }).join('\n');

  return (
    PREAMBLE('packages/schema/src/entities/index.ts') +
    `# Schema\n\n` +
    `Schema version \`${SCHEMA_VERSION}\`. ${CORE_ENTITIES.length} core record types.\n\n` +
    `Full field types, formats and constraints are in the\n` +
    `[API reference](../building/api.md), which is generated from the same\n` +
    `definitions. This page lists what each record asserts *beyond* the\n` +
    `envelope every record carries.\n\n` +
    `## The envelope\n\n` +
    `On every record, of every type:\n\n` +
    [...commons].map((f) => `- \`${f}\``).join('\n') +
    `\n\nWhy \`superseded_by\` is not among them — it is derived, never stored —\n` +
    `is [0002](../decisions/index.md).\n\n` +
    `## The records\n\n` +
    body +
    `\n> The schema is the only definition of what a record is. The kernel never\n` +
    `> restates a field, and neither does this page: it is generated from\n` +
    `> \`@clycites/schema\` on every build.\n`
  );
};

/* ── quality flags ────────────────────────────────────────────────────── */

const flags = () => {
  const rows = Object.entries(FLAG_GLOSSARY).sort(([a], [b]) => a.localeCompare(b));
  return (
    PREAMBLE('apps/kernel/src/records/lender-report.ts') +
    `# Quality flags\n\n` +
    `A flag is not a rejection. The kernel stores what it was told and records\n` +
    `what is wrong with it — [invariant 4](../concepts/record-model.md#flag-never-reject)\n` +
    `— because a record refused at the door is a record that exists only in the\n` +
    `head of the person who was turned away.\n\n` +
    `These are the words shown to a credit officer. The renderer refuses to\n` +
    `display a flag that has no entry here, so this list and the product cannot\n` +
    `drift apart.\n\n` +
    `| Flag | What it means |\n|---|---|\n` +
    rows.map(([flag, meaning]) => `| \`${flag}\` | ${meaning} |`).join('\n') +
    `\n`
  );
};

/* ── write ────────────────────────────────────────────────────────────── */

const outputs: Array<[string, string]> = [
  ['enumerations.md', enumerations()],
  ['schema.md', entities()],
  ['quality-flags.md', flags()],
];

for (const [name, content] of outputs) {
  writeFileSync(resolve(DOCS, name), content, 'utf8');
  console.log(`wrote docs/reference/${name}`);
}
